USE [master]
GO

/****** Object:  Database [SQLMonitoring]    Script Date: 24/06/2020 18:07:45 ******/
CREATE DATABASE [SQLMonitoring]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLMonitoring_Data_Primary', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Primary.mdf' , SIZE = 100MB , MAXSIZE = 10485760KB , FILEGROWTH = 1048576KB ), 
 FILEGROUP [DBM_FG_1]  DEFAULT
( NAME = N'SQLMonitoring_Data_Secondary1_1', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary1_1.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB ),
( NAME = N'SQLMonitoring_Data_Secondary1_2', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary1_2.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB ), 
 FILEGROUP [DBM_FG_2] 
( NAME = N'SQLMonitoring_Data_Secondary2_1', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary2_1.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB ),
( NAME = N'SQLMonitoring_Data_Secondary2_2', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary2_2.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB ), 
 FILEGROUP [DBM_FG_3] 
( NAME = N'SQLMonitoring_Data_Secondary3_1', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary3_1.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB ),
( NAME = N'SQLMonitoring_Data_Secondary3_2', FILENAME = N'C:\MountPoints\DatabaseMonitoring\SQLSERVER1\SQLMonitoring_Data_Secondary3_2.ndf' , SIZE = 3072KB , MAXSIZE = 104857600KB , FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'SQLMonitoring_Log', FILENAME = N'C:\MountPoints\LogsUserDBs\SQLSERVER1\SQLMonitoring_Log.ldf' , SIZE = 1024KB , MAXSIZE = 20971520KB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLMonitoring].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLMonitoring] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLMonitoring] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLMonitoring] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLMonitoring] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLMonitoring] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLMonitoring] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLMonitoring] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLMonitoring] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLMonitoring] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLMonitoring] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLMonitoring] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLMonitoring] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLMonitoring] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLMonitoring] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLMonitoring] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SQLMonitoring] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLMonitoring] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLMonitoring] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLMonitoring] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLMonitoring] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLMonitoring] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLMonitoring] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLMonitoring] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SQLMonitoring] SET  MULTI_USER 
GO

ALTER DATABASE [SQLMonitoring] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLMonitoring] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLMonitoring] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLMonitoring] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQLMonitoring] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLMonitoring] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SQLMonitoring] SET  READ_WRITE 
GO




