USE [master]
GO

/****** Object:  Database [StagingDBs]    Script Date: 24/06/2020 17:35:46 ******/
CREATE DATABASE [StagingDBs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StagingDBs_Data_Primary', FILENAME = N'C:\MountPoints\PrimariesUserDBs\SQLSERVER1\StagingDBs_Data_Primary.mdf' , SIZE = 100MB , MAXSIZE = 10485760KB , FILEGROWTH = 1048576KB ), 
 FILEGROUP [StagingDBs_FG_1]  DEFAULT
( NAME = N'StagingDBs_Data_Secondary1_1', FILENAME = N'C:\MountPoints\StagingDBs\StagingDBs1\SQLSERVER1\StagingDBs_Data_Primary.ndf' , SIZE = 1024MB , MAXSIZE = 104857600KB , FILEGROWTH = 102400KB ),
( NAME = N'StagingDBs_Data_Secondary1_2', FILENAME = N'C:\MountPoints\StagingDBs\StagingDBs2\SQLSERVER1\StagingDBs_Data_Secondary1_2.ndf' , SIZE = 1024MB, MAXSIZE = 104857600KB , FILEGROWTH = 102400KB )--,
--( NAME = N'StagingDBs_Data_Secondary1_3', FILENAME = N'C:\MountPoints\StagingDBs\StagingDBs3\SQLSERVER1\StagingDBs_Data_Secondary1_3.ndf' , SIZE = 100MB, MAXSIZE = 104857600KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'StagingDBs_Log', FILENAME = N'C:\MountPoints\LogsUserDBs\SQLSERVER1\StagingDBs_Log.ldf' , SIZE = 1024MB , MAXSIZE = 20971520KB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StagingDBs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StagingDBs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StagingDBs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StagingDBs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StagingDBs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StagingDBs] SET ARITHABORT OFF 
GO

ALTER DATABASE [StagingDBs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StagingDBs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StagingDBs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StagingDBs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StagingDBs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StagingDBs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StagingDBs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StagingDBs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StagingDBs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StagingDBs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StagingDBs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StagingDBs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StagingDBs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StagingDBs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StagingDBs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StagingDBs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StagingDBs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StagingDBs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StagingDBs] SET  MULTI_USER 
GO

ALTER DATABASE [StagingDBs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StagingDBs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StagingDBs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StagingDBs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StagingDBs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StagingDBs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StagingDBs] SET  READ_WRITE 
GO

